# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'FoodRand' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodRand
pod 'Alamofire'
pod 'AlamofireImage'
pod 'ReachabilitySwift'
pod 'CDYelpFusionKit', '2.1.1'
pod 'NVActivityIndicatorView/Extended'

end
